server:
  port: 8764
spring:
  application:
    name: zull
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    StudentManager: /s/**
    TeacherManager: /t/**