server:
  port: 8766
spring:
  application:
    name: fegin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true       #启用Fegin的服务容错机制